services:
  # Backend API (Express + TypeScript)
  - type: web
    name: spotify-challenge-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: apps/api
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      cd ../..
      pnpm install --frozen-lockfile
      cd apps/api
      pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_NAME
        value: sp_session
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health

  # Frontend Web (Next.js)
  - type: web
    name: spotify-challenge-web
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: apps/web
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      cd ../..
      pnpm install --frozen-lockfile
      cd apps/web
      pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false

